spring.application.name=Ecommerce



# ===============================

# = DATA SOURCE (TiDB - MySQL)

# ===============================

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=REQUIRED

spring.datasource.username=GbVyWayUgE89rDY.root
spring.datasource.password=RuGm1wIPOMfXQANY

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================

# = JPA / HIBERNATE

# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================

# = SERVER CONFIG

# ===============================

server.port=8070
